platform :ios, '8.0'

target "CZNews" do
 pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12’
pod 'MJExtension', '~> 3.0.13’
pod 'SDWebImage', '~> 4.0.0’
pod 'SVProgressHUD', '~> 2.1.2'
 pod 'MBProgressHUD', '~> 1.0.0'

end
